# Generated by Django 2.0.5 on 2019-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-review_data',)},
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_number',
        ),
        migrations.AddField(
            model_name='article',
            name='review_number',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数量'),
        ),
    ]
